### ISSUE TITLE
implement synchronization with remote block storage

### ISSUE THREAD

**Issue by hpk42** [nextleap-project/muacryptcc#15]
- block storage to live at a provider's site
- muacryptcc pushes new blocks to remote block server
- authentication for pushing to blockserver via user/password of IMAP login
- muacryptcc asks blockserver to give list of all blocks (using its authentication)

**Comment by azul** [comment]
We implemented this with a little difference in #33. Mainly the last point is replaced with using the remote server as a storage backend for Claimchain. A chain is instantiated with the url of the server and the head imprint of the chain. It can then retrieve the head which in turn references all the other blocks. This way the server remains a plain key-value store and we make use of claimchains logic. We use the filestore to cache the retrieved claims locally.
