### ISSUE TITLE
use own claimchain for peer info

### ISSUE THREAD

**Issue by azul** [nextleap-project/muacryptcc#20]
Currently we store the peer info in `self.addr2cc_info[addr]`. This will be empty when loading the account from disc.

Instead we should

- [x]  add pk to claim_about
- [x] retrieve pk from our own state
- [x] add claims when we see gossip
- [x] persist state even if we did not commit it
- [x] figure out what to do if autocrypt uses a different key than what we would expect in our own mails
- [ ] revoke read capabilities from state for everyone but the person a claim is about

**Comment by azul** [comment]
We actually might not need this if we can iterate over all our own claims and persist the store instead.

That way we could use our own claimchain to retrieve all peer info.

**Comment by azul** [comment]
Regarding "autocrypt uses a different key than what we would expect in our own mails"... 
We consider autocrypt the authorative source for which key to use. We only track those keys in our own claim chain.
Autocrypt will prefer directly received keys and over gossip. So Autocrypt picks a different key then what we expect in two situations:
* We saw gossip before but there also was a direct key available.
* The person lost their device or has a new key for some other reason.

If that leads to inconsistencies we will recommend verifying the contact in question... but we will not interfere with the selection Autocrypt performs on its own.

**Comment by hpk42** [comment]
On Sat, May 12, 2018 at 01:48 -0700, azul wrote:
> Regarding "autocrypt uses a different key than what we would expect in our own mails"... 
> We consider autocrypt the authorative source for which key to use. We only track those keys in our own claim chain.
> Autocrypt will prefer directly received keys and over gossip. So Autocrypt picks a different key then what we expect in two situations:
> * We saw gossip before but there also was a direct key available.
> * The person lost their device or has a new key for some other reason.
> 
> If that leads to inconsistencies we will recommend verifying the contact in question... but we will not interfere with the selection Autocrypt performs on its own.

that sounds like a good text fragement to include!
